apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - networkpolicies.yaml
  - externalsecret.yaml
  - wildcard-certificate.yaml
  - pushsecret-wildcard.yaml

# Values are handled via Helm in ArgoCD ApplicationSet
# This kustomization manages additional resources
