---
# Wildcard Certificate for *.cz.cc.rex5.ca
# This certificate is issued by cert-manager and used by Traefik
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cz-cc-rex5-ca
  namespace: rex5-cc-cz-k8s-traefik
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.cz.cc.rex5.ca"
    - "cz.cc.rex5.ca"
  # Renew 30 days before expiry
  renewBefore: 720h
